### ISSUE TITLE
Ctf protect interface

### ISSUE THREAD

**Issue by Lagetta** [blue-nebula/base#235] opened 2021-07-21 20:44 UTC
While playing capture the flag protect mode while holding the flag, you can't clearly see how long you and the enemy are holding the flag to get a point. Even if it's shown it is not visible enough.

I am thinking if it's possible to place it in these logos, or do it like in bomber a count down.
![image](https://user-images.githubusercontent.com/53313579/126554020-4ae92784-74a8-471b-96bb-ecc1f3af3b18.png)

**Comment by TheAssassin** [comment] 2021-07-21 21:38
Duplicate of #234.

**Closed by TheAssassin** 2021-07-21 21:38 UTC
