### ISSUE TITLE
non english versions

### ISSUE THREAD

**Issue by bmorel** [blue-nebula/base#164] opened 2020-07-26 15:34 UTC
game is, AFAIK only available to people understanding english and it's damn acronyms like AFAIK (as far as I know).

I can not see any technical reason to not use translatable strings when possible, especially in new commits.

**Comment by MoonPadUSer** [comment] 2020-07-28 05:05
how would that look like?

**Comment by bmorel** [comment] 2020-07-28 19:20
It's mostly about selecting a tool, and applying some call over all translatable strings. Like gettext.

**Comment by TheAssassin** [comment] 2020-07-28 20:22
Duplicate of #56.

**Closed by TheAssassin** 2020-07-28 20:22 UTC
